### ISSUE TITLE
$init keyname appeares on result automatically

### ISSUE THREAD

**Issue by omidmaldar** [jonschlinkert/omit-empty#7]
If all the items inside the object are Boolean then **"$init": true**  will be added to the output automatically

omitEmpty({ a: true, b: false}) -> { a: true, b: false, $init: true } 

Any comments why this happens?

**Comment by doowb** [comment]
I just installed the latest version from NPM and ran the code above and I don't see the `$init: true` being output:

![image](https://user-images.githubusercontent.com/995160/63952752-1def6980-ca4e-11e9-84a5-24df7ba21752.png)

Are you passing in a plan object? Or are you passing in an object that was created by something else that might have the `$init` property on it?

**Comment by omidmaldar** [comment]
I'm using version `1.0.0` and yes, the object I'm sending to omitEmpty is a subdocument which is returned by MongoDB. The subdoc/object has 6 fields all of Boolean type. I checked the output of Mongo on its find query as well as the original doc in db. None of them has the `$init`. It's added to object after  passing it to omitEmpty.

**Comment by doowb** [comment]
Will you do `console.log(Object.keys(subdocument));` before sending the `subdocument` to `omitEmpty`?

**Comment by omidmaldar** [comment]
I did.  I confirm that the $init is there before sending to omitEmpty. This is interesting, $init is there when I use `console.log(Object.keys(subdocument));` but not when I simply use `console.log(subdocument);` 
Does it have anything with boolean values on this specific document.  I never faced it on other cases.

**Comment by doowb** [comment]
> Does it have anything with boolean values on this specific document. I never faced it on other cases.

I don't know, but I think it's a value that MongoDB (or mongoose if you're using that as an ORM) puts on there to track if updates need to be sent to the database.

Depending on the library that you're using to access MongoDB, there should be a way to get just the JSON object from the "model instance" (I don't know what else to call that object). That object will probably be one that you can use to pass to `omitEmpty`.

I'm going to close this issue since it's not a bug in `omit-empty`. Feel free to open a new issue if you do find something else in `omit-empty`.

**Comment by omidmaldar** [comment]
Ok, I found it. I should have used `.toJSON()` This the output of Mongodb that have this additional key. If I use `subducument.toJSON()` then the `$init` disapears from it.  See here for example: https://spectrum.chat/mongodb/general/what-is-init-trying-to-pull-out-array-of-key-names-from-nested-object~91b2f6df-fd61-411d-8be3-cda6b3afdf9b

Thank you for your answer and help @doowb.
